import { thaiCanonicalTerms } from "@/lib/thai-terminology";

export type BackofficeModuleGroup = "identity" | "master" | "documents" | "inventory" | "settings";

export type BackofficeModuleConfig = {
  key: string;
  group: BackofficeModuleGroup;
  title: string;
  description: string;
  listPath: string;
  createPath?: string;
  detailPath?: (id: string) => string;
  kind?: string;
  sidebarLabel: string;
  eyebrow: string;
  emptyTitle: string;
  emptyDescription: string;
  actions?: string[];
  statuses?: string[];
};

export const backofficeModules: Record<string, BackofficeModuleConfig> = {
  authentication: {
    key: "authentication",
    group: "identity",
    title: "การยืนยันตัวตน",
    description: "จัดการการเข้าสู่ระบบ การอนุมัติผู้ใช้งาน และการดูแลสิทธิ์การเข้าถึงของทีม ORRY",
    listPath: "/admin/users",
    sidebarLabel: "ผู้ใช้งาน",
    eyebrow: "Identity & Access",
    emptyTitle: "ยังไม่มีผู้ใช้งานในระบบ",
    emptyDescription: "เพิ่มผู้ใช้งานผ่านหน้าผู้ดูแลระบบเพื่อเริ่มกระบวนการอนุมัติ",
    statuses: ["pending_approval", "active", "suspended", "reset_required"],
  },
  company_information: {
    key: "company_information",
    group: "settings",
    title: "ข้อมูลบริษัท",
    description: "ข้อมูลนิติบุคคล ข้อมูลภาษี และสาขาที่ใช้บนเอกสารบัญชีทั้งหมด",
    listPath: "/settings/company",
    sidebarLabel: "ข้อมูลบริษัท",
    eyebrow: "Company Information",
    emptyTitle: "ยังไม่มีข้อมูลบริษัท",
    emptyDescription: "บันทึกข้อมูลบริษัทเพื่อใช้เป็นข้อมูลผู้ออกเอกสาร",
  },
  contacts: {
    key: "contacts",
    group: "master",
    title: "ผู้ติดต่อ",
    description: "จัดการลูกค้า ผู้ขาย และคู่ค้าสำหรับทุกเอกสารในระบบ",
    listPath: "/contacts",
    createPath: "/contacts/new",
    detailPath: (id) => `/contacts/${id}`,
    sidebarLabel: "ผู้ติดต่อ",
    eyebrow: "Contacts",
    emptyTitle: "ยังไม่มีผู้ติดต่อ",
    emptyDescription: "เพิ่มผู้ติดต่อรายแรกเพื่อใช้กับใบเสนอราคา ใบกำกับภาษี และค่าใช้จ่าย",
    statuses: ["active", "inactive", "archived"],
  },
  products: {
    key: "products",
    group: "master",
    title: "สินค้าและบริการ",
    description: "รายการสินค้า บริการ หน่วยนับ ราคา และสถานะสต็อกของ ORRY",
    listPath: "/products",
    createPath: "/products/new",
    detailPath: (id) => `/products/${id}`,
    sidebarLabel: "สินค้าและบริการ",
    eyebrow: "Products & Services",
    emptyTitle: "ยังไม่มีสินค้าและบริการ",
    emptyDescription: "สร้างรายการสินค้าเพื่อเชื่อมกับเอกสารขาย รับเข้า และค่าใช้จ่าย",
    statuses: ["active", "inactive", "discontinued"],
  },
  quotations: {
    key: "quotations",
    group: "documents",
    title: "ใบเสนอราคา",
    description: "เอกสารเสนอราคาที่รองรับอนุมัติ ส่งเอกสาร แชร์ อีเมล และติดตามสถานะลูกค้า",
    listPath: "/documents/quotations",
    createPath: "/documents/quotations/new",
    detailPath: (id) => `/documents/quotations/${id}`,
    kind: "quotation",
    sidebarLabel: "ใบเสนอราคา",
    eyebrow: "Quotations",
    emptyTitle: "ยังไม่มีใบเสนอราคา",
    emptyDescription: "สร้างใบเสนอราคาแรกเพื่อเริ่ม pipeline การขาย",
    actions: ["create", "save_draft", "submit", "approve", "send", "share", "email", "duplicate", "print", "add_attachment"],
    statuses: ["draft", "pending_approval", "approved", "sent", "accepted", "rejected", "cancelled"],
  },
  billing_notes: {
    key: "billing_notes",
    group: "documents",
    title: thaiCanonicalTerms.billingNote,
    description: "จัดการการวางบิล เอกสารแนบ ประวัติการส่ง และการเชื่อมโยงกับใบกำกับภาษี",
    listPath: "/documents/billing-notes",
    createPath: "/documents/billing-notes/new",
    detailPath: (id) => `/documents/billing-notes/${id}`,
    kind: "billing_note",
    sidebarLabel: thaiCanonicalTerms.billingNote,
    eyebrow: "Billing Notes",
    emptyTitle: `ยังไม่มี${thaiCanonicalTerms.billingNote}`,
    emptyDescription: `สร้าง${thaiCanonicalTerms.billingNote}เพื่อจัดรอบการรับชำระของลูกค้า`,
    actions: ["create", "save_draft", "approve", "send", "share", "email", "duplicate", "print", "add_attachment"],
    statuses: ["draft", "approved", "sent", "billed", "cancelled"],
  },
  cash_invoices: {
    key: "cash_invoices",
    group: "documents",
    title: thaiCanonicalTerms.cashInvoice,
    description: "ติดตามการออกเอกสาร การรับชำระ และสถานะการชำระเงินของรายการเงินสด",
    listPath: "/documents/cash-invoices",
    createPath: "/documents/cash-invoices/new",
    detailPath: (id) => `/documents/cash-invoices/${id}`,
    kind: "cash_invoice",
    sidebarLabel: thaiCanonicalTerms.cashInvoice,
    eyebrow: "Cash Invoices",
    emptyTitle: `ยังไม่มี${thaiCanonicalTerms.cashInvoice}`,
    emptyDescription: `สร้าง${thaiCanonicalTerms.cashInvoice}เพื่อบันทึกการขายสดและการรับเงิน`,
    actions: ["create", "save_draft", "approve", "send", "record_receipt", "share", "email", "duplicate", "print", "add_attachment"],
    statuses: ["draft", "approved", "issued", "partially_paid", "paid", "cancelled"],
  },
  tax_invoices: {
    key: "tax_invoices",
    group: "documents",
    title: "ใบกำกับภาษี",
    description: "ออกใบกำกับภาษี พร้อมการเชื่อมโยงการรับชำระและติดตามครบกำหนด",
    listPath: "/documents/tax-invoices",
    createPath: "/documents/tax-invoices/new",
    detailPath: (id) => `/documents/tax-invoices/${id}`,
    kind: "tax_invoice",
    sidebarLabel: "ใบกำกับภาษี",
    eyebrow: "Tax Invoices",
    emptyTitle: "ยังไม่มีใบกำกับภาษี",
    emptyDescription: "ออกใบกำกับภาษีเพื่อใช้งานด้านภาษีขายและติดตามการรับชำระ",
    actions: ["create", "save_draft", "approve", "send", "record_receipt", "share", "email", "duplicate", "print", "add_attachment"],
    statuses: ["draft", "approved", "issued", "partially_paid", "paid", "overdue", "cancelled"],
  },
  receipts: {
    key: "receipts",
    group: "documents",
    title: "ใบเสร็จรับเงิน",
    description: "บันทึกการรับชำระเงิน ปิดรายการ และเก็บหลักฐานการรับเงินตามเอกสารต้นทาง",
    listPath: "/documents/receipts",
    createPath: "/documents/receipts/new",
    detailPath: (id) => `/documents/receipts/${id}`,
    kind: "receipt",
    sidebarLabel: "ใบเสร็จรับเงิน",
    eyebrow: "Receipts",
    emptyTitle: "ยังไม่มีใบเสร็จรับเงิน",
    emptyDescription: "สร้างใบเสร็จรับเงินเมื่อมีการรับชำระจากลูกค้า",
    actions: ["create", "save_draft", "send", "record_receipt", "share", "email", "duplicate", "print", "add_attachment"],
    statuses: ["draft", "issued", "settled", "cancelled"],
  },
  expenses: {
    key: "expenses",
    group: "documents",
    title: thaiCanonicalTerms.expense,
    description: "อนุมัติค่าใช้จ่าย บันทึกการจ่ายเงิน และติดตามสถานะเจ้าหนี้หรือค่าใช้จ่ายภายใน",
    listPath: "/documents/expenses",
    createPath: "/documents/expenses/new",
    detailPath: (id) => `/documents/expenses/${id}`,
    kind: "expense",
    sidebarLabel: thaiCanonicalTerms.expense,
    eyebrow: "Expenses",
    emptyTitle: "ยังไม่มีรายการค่าใช้จ่าย",
    emptyDescription: "สร้างรายการค่าใช้จ่ายเพื่อเข้าสู่ขั้นตอนอนุมัติและการจ่าย",
    actions: ["create", "save_draft", "submit", "approve", "record_payment", "share", "email", "duplicate", "print", "add_attachment"],
    statuses: ["draft", "pending_approval", "approved", "partially_paid", "paid", "cancelled"],
  },
  purchase_orders: {
    key: "purchase_orders",
    group: "documents",
    title: "ใบสั่งซื้อ",
    description: "สั่งซื้อกับผู้ขาย ติดตามการส่งคำสั่งซื้อและสถานะการรับเข้าสินค้า",
    listPath: "/documents/purchase-orders",
    createPath: "/documents/purchase-orders/new",
    detailPath: (id) => `/documents/purchase-orders/${id}`,
    kind: "purchase_order",
    sidebarLabel: "ใบสั่งซื้อ",
    eyebrow: "Purchase Orders",
    emptyTitle: "ยังไม่มีใบสั่งซื้อ",
    emptyDescription: "สร้างใบสั่งซื้อเพื่อวางแผนรับเข้าสินค้าและจ่ายเจ้าหนี้",
    actions: ["create", "save_draft", "approve", "send", "duplicate", "print", "add_attachment"],
    statuses: ["draft", "approved", "sent", "partially_received", "received", "cancelled"],
  },
  receiving_inventory: {
    key: "receiving_inventory",
    group: "inventory",
    title: "รับเข้าสินค้า",
    description: "รับสินค้าเข้าคลังหลัก บันทึก movement สต็อก และผูกกับใบสั่งซื้อที่เกี่ยวข้อง",
    listPath: "/inventory/receivings",
    createPath: "/inventory/receivings/new",
    detailPath: (id) => `/inventory/receivings/${id}`,
    sidebarLabel: "รับเข้าสินค้า",
    eyebrow: "Receiving Inventory",
    emptyTitle: "ยังไม่มีรายการรับเข้า",
    emptyDescription: "สร้างรายการรับเข้าเพื่อปรับยอดคงเหลือของคลังหลัก",
    actions: ["create", "save_draft", "approve", "duplicate", "print", "add_attachment"],
    statuses: ["draft", "approved", "received", "cancelled"],
  },
  withholding_tax: {
    key: "withholding_tax",
    group: "documents",
    title: "ภาษีหัก ณ ที่จ่าย",
    description: "จัดทำหนังสือรับรองหัก ณ ที่จ่าย พร้อมบันทึกประวัติการออกเอกสารและการแชร์",
    listPath: "/documents/withholding-tax",
    createPath: "/documents/withholding-tax/new",
    detailPath: (id) => `/documents/withholding-tax/${id}`,
    sidebarLabel: "ภาษีหัก ณ ที่จ่าย",
    eyebrow: "Withholding Tax",
    emptyTitle: "ยังไม่มีหนังสือหัก ณ ที่จ่าย",
    emptyDescription: "สร้างเอกสารเพื่อบันทึกภาษีหัก ณ ที่จ่ายตามคู่ค้า",
    actions: ["create", "save_draft", "approve", "send", "share", "email", "duplicate", "print", "add_attachment"],
    statuses: ["draft", "approved", "issued", "cancelled"],
  },
  bank_accounts: {
    key: "bank_accounts",
    group: "settings",
    title: "บัญชีธนาคาร",
    description: `จัดการบัญชีธนาคาร ช่องทางชำระเงิน และ${thaiCanonicalTerms.bankAccountMapping}`,
    listPath: "/settings/bank-accounts",
    createPath: "/settings/bank-accounts/new",
    detailPath: (id) => `/settings/bank-accounts/${id}`,
    sidebarLabel: "บัญชีธนาคาร",
    eyebrow: "Bank Accounts",
    emptyTitle: "ยังไม่มีบัญชีธนาคาร",
    emptyDescription: "เพิ่มบัญชีธนาคารสำหรับออกเอกสารและรับชำระเงิน",
    statuses: ["active", "inactive"],
  },
};

const moduleKeyAliases: Record<string, keyof typeof backofficeModules> = {
  quotation: "quotations",
  billing_note: "billing_notes",
  cash_invoice: "cash_invoices",
  tax_invoice: "tax_invoices",
  receipt: "receipts",
  expense: "expenses",
  purchase_order: "purchase_orders",
  inventory_receiving: "receiving_inventory",
  withholding_tax: "withholding_tax",
};

export function getModuleConfig(key: string) {
  return backofficeModules[key] ?? backofficeModules[moduleKeyAliases[key]];
}

export const documentModuleKeys = [
  "quotations",
  "billing_notes",
  "cash_invoices",
  "tax_invoices",
  "receipts",
  "expenses",
  "purchase_orders",
  "withholding_tax",
] as const;
